### ISSUE TITLE
Redesign the Shifter PCB

### ISSUE THREAD

**Issue by janc18** [janc18/CAE32#16]
To meet standard features without incurring extra costs from the PCB manufacturer

**Comment by HUANGJIN169** [comment]
very good

**Comment by janc18** [comment]
# Change-log *Shifter_PCB_v1.2.1*

- Replace the Pin Headers for FCP connectors
- Changed via diameter from 0.15 to 0.3mm
- Changed BOOT button position
- Replace all the GND Pin Headers for just 3 Pin Sockets

![Shifter](https://github.com/janc18/CAE32/assets/43817922/0759ae9d-aa32-4481-b317-541f5bfef0cc)
