### ISSUE TITLE
Calcular consumo de PCB

### ISSUE THREAD

**Issue by janc18** [janc18/CAE32#3]
Revisar en la hoja de datos de cada componte (IC's) su consumo(mAh) y anotarlo en el esquema eléctrico

**Comment by janc18** [comment]
El consumo aproximado es:
|Componente|Consumo|Cantidad|
|-|-|-|
|MCU|120 mA|1|
|REF3033|50uA|1|
|ADC128S102|3.1mA|1|
|HX711|1500ua|3|

**Consumo total en primera revisión:128mA**

**Comment by HUANGJIN169** [comment]
Very good. When will the direct drive PCB be updated?

**Comment by janc18** [comment]
@HUANGJIN169 Hi, I haven't started yet the development of the Direct drive PCB, I just finished the Pedals PCB version 2 about two moths ago, but i haven't tested it yet, I need to get the PCB manufactured, assembly and firmware programming but I can't do it right now, tomorrow i will update the CAE32 docs with an English version, for now please give a check:https://cae32-docs.readthedocs.io/es/latest/

**Comment by janc18** [comment]
Please review de Documentation,which is now available English. https://cae32-docs.readthedocs.io

**Comment by HUANGJIN169** [comment]
Ok, thank you for your reply. I also look forward to your direct drive PCB

**Comment by HUANGJIN169** [comment]
Hello, how can I contact you, such as Facebook or Twitter and no China WeChat?

**Comment by janc18** [comment]
Hi @HUANGJIN169 , you can contact me through Discord. This is my username:eling.
But if you can't use Discord I can create a Twitter account

**Comment by janc18** [comment]
Twitter account: ElingJAg

**Comment by HUANGJIN169** [comment]
You can add my friend through Discord. My user name is:simracingos#6659
